apiVersion: v1
kind: ConfigMap
metadata:
  name: caravan-config

data:
  BASE_URL: "http://localhost:3000"
  DB_PREFIX: "mysql"
  DB_NAME: "soa_explore_caravan_parks"
  CAMPGROUND_API_URL: "https://ridb.recreation.gov/api/v1/facilities" 